### ISSUE TITLE
Sign up/in through Github redirects to 404

### ISSUE THREAD

**Issue by gerardogalvez** [ruby-rcade/RubyGameDev.com#39]
Clicking the "Sign up with your GitHub account" in /sign_up and "Sign in through GitHub" in /sign_in redirects the user to 404.html.
![capture](https://cloud.githubusercontent.com/assets/8509232/8606339/98b96c48-2650-11e5-9bcd-fbe72cf6a42f.PNG)

**Comment by andrewhavens** [comment]
Interesting...when I sign in using GitHub it works. I think this error might be that we have not defined what to do for the `/auth/failure` route. I see in the URL params `message=invalid_credentials`. Can you confirm that you entered your username/password correctly on GitHub?

**Comment by gerardogalvez** [comment]
This happens when I'm already logged in in Github and try to sign up at rubygamedev.com through GitHub.

**Comment by gerardogalvez** [comment]
Nevermind, I'm pretty sure I was doing something wrong hahaha, sorry.

**Comment by andrewhavens** [comment]
I actually figured out what was going on here. I was using Safari, which was automatically redirecting to `https`, but I was able to reproduce the issue in Chrome which was staying on `http`. The registered GitHub redirect URI was set to https so it would fail if you were redirected from http. I have applied a config setting to redirect all http requests to https.
