### ISSUE TITLE
Error with Body markdown in Posts if missing 

### ISSUE THREAD

**Issue by soff22** [ruby-rcade/RubyGameDev.com#42]
Hi Andrew,
in class <b>Post</b> `body_markdown` is a compulsory field to fill in https://github.com/ruby-rcade/RubyGameDev.com/blob/master/app/models/post.rb#L8-11
We can fix it in two ways:
- with if clause in the `before_save` block
- with validates_presence_of `:body_markdown`
- if you have another way to fix it, please share with us<br/><br/>
Please advise how to proceed.<br/>
Thank you

**Comment by andrewhavens** [comment]
Ah, there was a time where it was not required, but now it is. Please add a validator to require the body_markdown
