### ISSUE TITLE
Site appears to be down

### ISSUE THREAD

**Issue by tomprats** [ruby-rcade/RubyGameDev.com#53]
I get the classic Rails error: "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**Comment by andrewhavens** [comment]
Hmm...thanks for the report. It seems to be working for me. Was there a specific page/URL that you visited that is not working?

**Comment by tomprats** [comment]
I'm just going to https://www.rubygamedev.com/ by clicking the link at the top of the GitHub page. Thought it could be a really old session messing it up but it didn't work in Incognito either

**Comment by andrewhavens** [comment]
Ah, could be because I'm logged in and you're not. I think there may be a fix for this in an open PR: https://github.com/RailsGEnthusiasts/RubyGameDev.com/commit/0936f2141402d142519e884a9a7fc902f59298e9#diff-861e2a05ddaf0f1781c390733649280dR2

**Comment by andrewhavens** [comment]
@tomprats Please try again now that some PRs have been merged.

**Comment by tomprats** [comment]
Works! Thanks a lot
