### ISSUE TITLE
Custom 404 and 500 error pages

### ISSUE THREAD

**Issue by tomprats** [ruby-rcade/RubyGameDev.com#54]
I'd like to start contributing to this project but noticed there's an error. It gave me the idea to possibly have custom error pages. This is obviously more design focused but I thought I'd just throw it out there.

Also let me know if there's something you'd like me to start on! (I'd wrestle the current error but have no access to any logs)

**Comment by andrewhavens** [comment]
Thanks @tomprats! We've been working on a fancy new design ([sneak peak here](https://invis.io/9Y3SRF4BJ)), but we haven't considered 404 or 500 error pages yet. That's a good idea. We could probably have some fun with it.
