### ISSUE TITLE
Tons of Emails

### ISSUE THREAD

**Issue by tomprats** [ruby-rcade/RubyGameDev.com#71]
I'm getting a lot of weekly digest emails, pretty sporadically. Seems like someone might be testing something or a job is being triggered too often. Looks like it's 19 since May 13th. My email address getting hit is tom@tomprats.com.

Thanks,
Tom

**Comment by andrewhavens** [comment]
Thanks for reporting this Tom. I will look into this.

**Comment by andrewhavens** [comment]
Hey @tomprats, sorry this project has been on my todo list for a long time. Are you still receiving these emails at odd times? Or did the issue resolve itself?

**Comment by tomprats** [comment]
I checked earlier today and didn't see any recent ones, so I think it must've resolved itself
