### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by tomprats** [ruby-rcade/RubyGameDev.com#73]
Looks like the feed is currently overwhelmed by spam. The twitter account is tweeting it out too, so it might be good to disable that. Not sure if the project is dead or not, but currently the website is being misused

**Comment by andrewhavens** [comment]
Thanks for letting me know @tomprats! I hadn't checked it in a while. I'll work on cleaning it up. Might need to add some sort of captcha validation to sign up.
